-- AlterTable
ALTER TABLE "track_metadata" ALTER COLUMN "era" DROP NOT NULL,
ALTER COLUMN "emotion" DROP NOT NULL,
ALTER COLUMN "energy" DROP NOT NULL,
ALTER COLUMN "mood" DROP NOT NULL,
ALTER COLUMN "mood" SET DATA TYPE TEXT,
ALTER COLUMN "instruments" DROP NOT NULL,
ALTER COLUMN "instruments" SET DATA TYPE TEXT,
ALTER COLUMN "bpm" DROP NOT NULL,
ALTER COLUMN "key" DROP NOT NULL;
