-- AlterTable
ALTER TABLE "likes" ADD COLUMN     "amount" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "created" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
