-- AlterTable
ALTER TABLE "note_attachments" ALTER COLUMN "albumID" DROP NOT NULL,
ALTER COLUMN "noteMediaID" DROP NOT NULL,
ALTER COLUMN "trackID" DROP NOT NULL,
ALTER COLUMN "userID" DROP NOT NULL;
